[tool.poetry]
name = "make_gtfs"
version = "2.1.0"
description = "A Python 3.6+ library to build GTFS feeds from basic route information."
authors = ["Alex Raichev <araichev@mrcagney.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6|^3.7"
gtfs_kit = "^2.0"

[tool.poetry.dev-dependencies]
jupyter = "^1.0"
pytest = "^5.2"
pre-commit = "^1.18"
black = "=19.3b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
make_gtfs = "make_gtfs.cli:make_gtfs"